export const ADD_LANDLORD = "ADD_LANDLORD";
export const RETRIEVE_LANDLORDS = "RETRIEVE_LANDLORDS";
export const UPDATE_LANDLORD = "UPDATE_LANDLORD";
export const DELETE_LANDLORD = "DELETE_LANDLORD";

export const ADD_FLATBOOKING = "ADD_FLATBOOKING";
export const RETRIEVE_FLATBOOKING = "RETRIEVE_FLATBOOKING";
export const UPDATE_FLATBOOKING = "UPDATE_FLATBOOKING";
export const DELETE_FLATBOOKING = "DELETE_FLATBOOKING";

export const ADD_FLAT = "ADD_FLAT";
export const RETRIEVE_FLATS = "RETRIEVE_FLATS";
export const UPDATE_FLAT = "UPDATE_FLAT";
export const DELETE_FLAT = "DELETE_FLAT";

export const ADD_TENANT = "ADD_TENANT";
export const RETRIEVE_TENANTS = "RETRIEVE_TENANTS";
export const UPDATE_TENANT = "UPDATE_TENANT";
export const DELETE_TENANT = "DELETE_TENANT";